/* Database schema to keep the structure of entire database. */

CREATE TABLE animals (
    id INT GENERATED BY DEFAULT AS IDENTITY,   
    name VARCHAR(100) NOT NULL,  
    date_of_birth DATE,   
    escape_attempt INT, 
    neutered BIT, 
    weight_kg DECIMAL(5,2)     
   
    
); ALTER TABLE animals ADD COLUMN species VARCHAR(50);


CREATE TABLE owners(id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,full_name VARCHAR(100) NOT NULL, age INT);          
CREATE TABLE owners(id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(100) NOT NULL);                          

-- modify animals table
ALTER TABLE animals ADD PRIMARY KEY (id);
ALTER TABLE animals DROP COLUMN species; 
ALTER TABLE animals ADD COLUMN species_id INT REFERENCES species(id);       
 ALTER TABLE animals ADD COLUMN owner_id INT REFERENCES owners(id);              